export * from "./deleteFavoriteAdvice"
export * from "./getAdviceById"
export * from "./getAllFavorites"
export * from "./getDailyAdvice"
export * from "./getRandomAdvice"
export * from "./postFavoriteAdvice"
